apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      run: testp
  template:
    metadata:
      labels:
        run: testp
    spec:
      containers:
      - name: frontend
        image: uojha/client-app:latest
        ports:
        - containerPort: 80

apiVersion: v1
kind: Service
metadata:
  name: frontend-service

spec:
  type: NodePort
  selector:
    run: testp
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007